import Head from 'next/head';
import Team from '@/components/team';
import About from '@/components/about';
import Footer from '@/components/footer';
import HomeBless from '@/components/home';
import BookNow from '@/components/bookNow';
import Grooming from '@/components/grooming';
import Services from '@/components/servicesSec';
import Loading from '@/components/loading/loading';
import Testimonials from '@/components/testimonials';

export default function Home() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <Loading />
                <HomeBless />
                <About />
                <BookNow />
                <Services />
                <Grooming />
                <Team />
                <Testimonials />
                <Footer />
            </main>
        </>
    );
}
